
package mysql_crud;

import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.*;
import javax.swing.JOptionPane;

public class signup extends javax.swing.JFrame {
    
    conexion cn = new conexion();
    
    public signup() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        userName = new javax.swing.JTextField();
        name = new javax.swing.JTextField();
        telephone = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        Password = new javax.swing.JPasswordField();
        VerifyPassword = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        Cancelar = new javax.swing.JButton();
        LabelTitulo = new javax.swing.JLabel();
        aceptar = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        SideContainer = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(223, 223, 223));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("DM Sans", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Nombre de Usuario");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, -1, -1));

        jLabel7.setFont(new java.awt.Font("DM Sans", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Nombre Completo");
        jLabel7.setAlignmentY(0.0F);
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 168, -1, -1));

        jLabel8.setFont(new java.awt.Font("DM Sans", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Numero de Telefono");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 226, -1, -1));

        jLabel9.setFont(new java.awt.Font("DM Sans", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Correo Electronico");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 286, -1, -1));

        jLabel10.setFont(new java.awt.Font("DM Sans", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Contraseña");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 343, -1, 20));

        jLabel11.setFont(new java.awt.Font("DM Sans", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Confirmar contraseña");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 402, -1, -1));

        userName.setBackground(new java.awt.Color(71, 71, 71));
        userName.setFont(new java.awt.Font("DM Sans", 0, 14)); // NOI18N
        userName.setForeground(new java.awt.Color(255, 255, 255));
        userName.setAlignmentX(0.0F);
        userName.setAlignmentY(0.0F);
        userName.setBorder(null);
        userName.setOpaque(false);
        jPanel1.add(userName, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 137, 210, -1));

        name.setBackground(new java.awt.Color(71, 71, 71));
        name.setFont(new java.awt.Font("DM Sans", 0, 14)); // NOI18N
        name.setForeground(new java.awt.Color(255, 255, 255));
        name.setAlignmentX(0.0F);
        name.setBorder(null);
        name.setOpaque(false);
        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });
        jPanel1.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 195, 210, -1));

        telephone.setBackground(new java.awt.Color(71, 71, 71));
        telephone.setFont(new java.awt.Font("DM Sans", 0, 14)); // NOI18N
        telephone.setForeground(new java.awt.Color(255, 255, 255));
        telephone.setAlignmentX(0.0F);
        telephone.setBorder(null);
        telephone.setOpaque(false);
        jPanel1.add(telephone, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 254, 210, -1));

        email.setBackground(new java.awt.Color(71, 71, 71));
        email.setFont(new java.awt.Font("DM Sans", 0, 14)); // NOI18N
        email.setForeground(new java.awt.Color(255, 255, 255));
        email.setAlignmentX(0.0F);
        email.setBorder(null);
        email.setOpaque(false);
        jPanel1.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 313, 210, -1));

        Password.setBackground(new java.awt.Color(71, 71, 71));
        Password.setForeground(new java.awt.Color(255, 255, 255));
        Password.setBorder(null);
        Password.setOpaque(false);
        jPanel1.add(Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 372, 210, -1));

        VerifyPassword.setBackground(new java.awt.Color(71, 71, 71));
        VerifyPassword.setForeground(new java.awt.Color(255, 255, 255));
        VerifyPassword.setBorder(null);
        VerifyPassword.setOpaque(false);
        jPanel1.add(VerifyPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 430, 210, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mysql_crud/images/imagen2.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(582, 82, -1, -1));

        Cancelar.setFont(new java.awt.Font("DM Sans", 0, 16)); // NOI18N
        Cancelar.setForeground(new java.awt.Color(255, 255, 255));
        Cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mysql_crud/images/icon less.png"))); // NOI18N
        Cancelar.setText("Cancelar Proceso");
        Cancelar.setBorder(null);
        Cancelar.setContentAreaFilled(false);
        Cancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelarActionPerformed(evt);
            }
        });
        jPanel1.add(Cancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 530, -1, -1));

        LabelTitulo.setBackground(new java.awt.Color(255, 255, 255));
        LabelTitulo.setFont(new java.awt.Font("DM Sans", 1, 25)); // NOI18N
        LabelTitulo.setForeground(new java.awt.Color(255, 255, 255));
        LabelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelTitulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mysql_crud/images/header.png"))); // NOI18N
        LabelTitulo.setText("Registro de nuevo administrador");
        LabelTitulo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(LabelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 915, 47));

        aceptar.setFont(new java.awt.Font("DM Sans", 1, 16)); // NOI18N
        aceptar.setForeground(new java.awt.Color(255, 255, 255));
        aceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mysql_crud/images/button1.png"))); // NOI18N
        aceptar.setText("Empezemos");
        aceptar.setBorder(null);
        aceptar.setContentAreaFilled(false);
        aceptar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        aceptar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptarActionPerformed(evt);
            }
        });
        jPanel1.add(aceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(368, 509, -1, -1));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mysql_crud/images/imagen3.png"))); // NOI18N
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(374, 372, -1, -1));

        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mysql_crud/images/frase2.png"))); // NOI18N
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(335, 108, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mysql_crud/images/textarea.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 132, -1, -1));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mysql_crud/images/textarea.png"))); // NOI18N
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 190, -1, -1));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mysql_crud/images/textarea.png"))); // NOI18N
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 249, -1, -1));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mysql_crud/images/textarea.png"))); // NOI18N
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 308, -1, -1));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mysql_crud/images/textarea.png"))); // NOI18N
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 366, -1, -1));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mysql_crud/images/textarea.png"))); // NOI18N
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 424, -1, -1));

        jSeparator1.setBackground(new java.awt.Color(99, 99, 99));
        jSeparator1.setForeground(new java.awt.Color(99, 99, 99));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 80, 1, 448));

        jButton1.setFont(new java.awt.Font("DM Sans", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(153, 153, 153));
        jButton1.setText("Limpiar");
        jButton1.setAlignmentY(0.0F);
        jButton1.setBorder(null);
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 460, -1, -1));

        SideContainer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mysql_crud/images/menu2.png"))); // NOI18N
        jPanel1.add(SideContainer, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 47, 564, 528));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelarActionPerformed
        Login login = new Login();
        this.setVisible(false);
        login.setVisible(true);
    }//GEN-LAST:event_CancelarActionPerformed

    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameActionPerformed

    private void aceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptarActionPerformed
        String Usuario = userName.getText();
        String Nombre = name.getText();
        String Telefono = telephone.getText();
        String Correo = email.getText();
        String Contrasena = new String(Password.getPassword());
        String VerificarContrasena = new String(VerifyPassword.getPassword());
        /*...*/
        System.out.println(Contrasena+" <----> "+VerificarContrasena); 

        if (Usuario.equals("") || Nombre.equals("") || Telefono.equals("") || Correo.equals("") || Contrasena.equals("") || VerificarContrasena.equals("")){
            JOptionPane.showMessageDialog(null, "Porfabor, llene todas las casillas antes de continuar!");
        }else {
            if (Contrasena.equals(VerificarContrasena)){
                try {
                    Connection con = cn.conexion();
                    PreparedStatement pps = con.prepareStatement("INSERT INTO administrador(nombreUsuario, nombreCompleto, telefono, correo, contrasena) VALUES (?,?,?,?,?)");
                    pps.setString(1, Usuario);
                    pps.setString(2, Nombre);
                    pps.setString(3, Telefono);
                    pps.setString(4, Correo);
                    pps.setString(5, Contrasena);
                    pps.executeUpdate();
                    JOptionPane.showMessageDialog(null, "Felicidades, se la logrado registrar Correctamente!");
                    Tabla tabla = new Tabla();
                    tabla.setVisible(true);
                    this.setVisible(false);

                } catch (SQLException ex) {
                    Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else {
                JOptionPane.showMessageDialog(null, "Las contraseñas no coinciden!");
            }
        }

        
    }//GEN-LAST:event_aceptarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        userName.setText("");
        name.setText("");
        telephone.setText("");
        email.setText("");
        Password.setText("");
        VerifyPassword.setText("");
        /*LabelTitulo.setText("");*/
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new signup().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cancelar;
    private javax.swing.JLabel LabelTitulo;
    private javax.swing.JPasswordField Password;
    private javax.swing.JLabel SideContainer;
    private javax.swing.JPasswordField VerifyPassword;
    private javax.swing.JButton aceptar;
    private javax.swing.JTextField email;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField name;
    private javax.swing.JTextField telephone;
    private javax.swing.JTextField userName;
    // End of variables declaration//GEN-END:variables
}
