package mysql_crud;

import javax.swing.JOptionPane;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

public class Tabla extends javax.swing.JFrame {

    conexion con1 = new conexion();
    DefaultTableModel modelo;
    Statement st;
    ResultSet rs;
    
    String nuevo_nombre;
    
    public Tabla() {
        initComponents();
        
        consultar();
    }
    
    private String getNombre(){
        return nuevo_nombre;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        userName = new javax.swing.JTextField();
        name = new javax.swing.JTextField();
        telephone = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        Password = new javax.swing.JPasswordField();
        ID = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        CerrarSesion = new javax.swing.JButton();
        Limpiar = new javax.swing.JButton();
        agregar = new javax.swing.JButton();
        editar = new javax.swing.JButton();
        eliminar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Contenedor = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        javax.swing.JLabel nombreCompleto = new javax.swing.JLabel();
        Subtitulo = new javax.swing.JLabel();
        SideMenu = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("frameTabla"); // NOI18N
        setSize(new java.awt.Dimension(915, 575));

        jPanel1.setBackground(new java.awt.Color(223, 223, 223));
        jPanel1.setPreferredSize(new java.awt.Dimension(915, 575));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mysql_crud/images/settings.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 143, -1, -1));

        jLabel1.setFont(new java.awt.Font("DM Sans", 1, 25)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mysql_crud/images/header.png"))); // NOI18N
        jLabel1.setText("     Inicio para administradores (REGISTRO DE CLIENTES)");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 915, 47));

        jLabel4.setFont(new java.awt.Font("DM Sans Medium", 0, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("Opciones");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 137, 130, -1));

        jLabel5.setFont(new java.awt.Font("DM Sans Medium", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Nombre Completo");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 234, -1, -1));

        jLabel6.setFont(new java.awt.Font("DM Sans Medium", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Nombre de Usuario");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 176, -1, -1));

        jLabel8.setFont(new java.awt.Font("DM Sans Medium", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Numero de Telefono");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 293, -1, -1));

        jLabel9.setFont(new java.awt.Font("DM Sans Medium", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Correo Electronico");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 352, -1, -1));

        jLabel10.setFont(new java.awt.Font("DM Sans Medium", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Contraseña");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 410, -1, -1));

        jSeparator1.setBackground(new java.awt.Color(0, 102, 102));
        jSeparator1.setForeground(new java.awt.Color(0, 102, 102));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 168, 211, 1));

        userName.setBackground(new java.awt.Color(71, 71, 71));
        userName.setFont(new java.awt.Font("DM Sans", 0, 14)); // NOI18N
        userName.setForeground(new java.awt.Color(255, 255, 255));
        userName.setBorder(null);
        userName.setOpaque(false);
        jPanel1.add(userName, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 205, 120, -1));

        name.setBackground(new java.awt.Color(71, 71, 71));
        name.setFont(new java.awt.Font("DM Sans", 0, 14)); // NOI18N
        name.setForeground(new java.awt.Color(255, 255, 255));
        name.setBorder(null);
        name.setOpaque(false);
        jPanel1.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 263, 180, -1));

        telephone.setBackground(new java.awt.Color(71, 71, 71));
        telephone.setFont(new java.awt.Font("DM Sans", 0, 14)); // NOI18N
        telephone.setForeground(new java.awt.Color(255, 255, 255));
        telephone.setBorder(null);
        telephone.setOpaque(false);
        jPanel1.add(telephone, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 322, 180, -1));

        email.setBackground(new java.awt.Color(71, 71, 71));
        email.setFont(new java.awt.Font("DM Sans", 0, 14)); // NOI18N
        email.setForeground(new java.awt.Color(255, 255, 255));
        email.setBorder(null);
        email.setOpaque(false);
        jPanel1.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 381, 180, -1));

        Password.setBackground(new java.awt.Color(71, 71, 71));
        Password.setForeground(new java.awt.Color(255, 255, 255));
        Password.setBorder(null);
        Password.setOpaque(false);
        jPanel1.add(Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 440, 180, -1));

        ID.setEditable(false);
        ID.setBackground(new java.awt.Color(71, 71, 71));
        ID.setFont(new java.awt.Font("DM Sans", 1, 14)); // NOI18N
        ID.setForeground(new java.awt.Color(204, 204, 204));
        ID.setBorder(null);
        ID.setEnabled(true);
        ID.setOpaque(false);
        jPanel1.add(ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 205, 30, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mysql_crud/images/textarea2.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 200, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mysql_crud/images/textarea2.png"))); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 258, -1, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mysql_crud/images/textarea2.png"))); // NOI18N
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 317, -1, -1));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mysql_crud/images/textarea2.png"))); // NOI18N
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 376, -1, -1));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mysql_crud/images/textarea2.png"))); // NOI18N
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 434, 198, 29));

        CerrarSesion.setFont(new java.awt.Font("DM Sans", 1, 14)); // NOI18N
        CerrarSesion.setForeground(new java.awt.Color(255, 255, 255));
        CerrarSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mysql_crud/images/bx_exit.png"))); // NOI18N
        CerrarSesion.setText("Cerrar Sesión");
        CerrarSesion.setBorder(null);
        CerrarSesion.setContentAreaFilled(false);
        CerrarSesion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CerrarSesionActionPerformed(evt);
            }
        });
        jPanel1.add(CerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 540, -1, -1));

        Limpiar.setFont(new java.awt.Font("DM Sans", 1, 12)); // NOI18N
        Limpiar.setForeground(new java.awt.Color(0, 153, 153));
        Limpiar.setText("Limpiar");
        Limpiar.setToolTipText("");
        Limpiar.setBorder(null);
        Limpiar.setContentAreaFilled(false);
        Limpiar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LimpiarActionPerformed(evt);
            }
        });
        jPanel1.add(Limpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 470, -1, -1));

        agregar.setFont(new java.awt.Font("DM Sans Medium", 0, 16)); // NOI18N
        agregar.setForeground(new java.awt.Color(255, 255, 255));
        agregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mysql_crud/images/button1.png"))); // NOI18N
        agregar.setText("Agregar");
        agregar.setBorder(null);
        agregar.setContentAreaFilled(false);
        agregar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        agregar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarActionPerformed(evt);
            }
        });
        jPanel1.add(agregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 440, -1, -1));

        editar.setFont(new java.awt.Font("DM Sans Medium", 0, 16)); // NOI18N
        editar.setForeground(new java.awt.Color(255, 255, 255));
        editar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mysql_crud/images/button1.png"))); // NOI18N
        editar.setText("Modificar");
        editar.setBorder(null);
        editar.setContentAreaFilled(false);
        editar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        editar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarActionPerformed(evt);
            }
        });
        jPanel1.add(editar, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 440, -1, -1));

        eliminar.setFont(new java.awt.Font("DM Sans Medium", 0, 16)); // NOI18N
        eliminar.setForeground(new java.awt.Color(255, 255, 255));
        eliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mysql_crud/images/button1.png"))); // NOI18N
        eliminar.setText("Eliminar");
        eliminar.setBorder(null);
        eliminar.setContentAreaFilled(false);
        eliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        eliminar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarActionPerformed(evt);
            }
        });
        jPanel1.add(eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 440, -1, -1));

        Contenedor.setFont(new java.awt.Font("DM Sans", 0, 12)); // NOI18N
        Contenedor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Username", "Nombre Completo", "Telefono", "Correo Electronico", "Contrasena"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        Contenedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ContenedorMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Contenedor);
        if (Contenedor.getColumnModel().getColumnCount() > 0) {
            Contenedor.getColumnModel().getColumn(0).setResizable(false);
            Contenedor.getColumnModel().getColumn(0).setPreferredWidth(10);
            Contenedor.getColumnModel().getColumn(1).setResizable(false);
            Contenedor.getColumnModel().getColumn(1).setPreferredWidth(40);
            Contenedor.getColumnModel().getColumn(2).setResizable(false);
            Contenedor.getColumnModel().getColumn(3).setResizable(false);
            Contenedor.getColumnModel().getColumn(4).setResizable(false);
            Contenedor.getColumnModel().getColumn(5).setResizable(false);
        }

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 90, 610, 340));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mysql_crud/images/user.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 59, -1, -1));

        nombreCompleto.setFont(new java.awt.Font("DM Sans Medium", 0, 14)); // NOI18N
        nombreCompleto.setForeground(new java.awt.Color(255, 255, 255));
        String nombre = getNombre();
        nombreCompleto.setText("Bienvenido Admin");
        jPanel1.add(nombreCompleto, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 59, -1, -1));

        Subtitulo.setBackground(new java.awt.Color(0, 153, 153));
        Subtitulo.setFont(new java.awt.Font("DM Sans", 0, 10)); // NOI18N
        Subtitulo.setForeground(new java.awt.Color(0, 153, 153));
        Subtitulo.setText("Administrador");
        jPanel1.add(Subtitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 76, -1, -1));

        SideMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mysql_crud/images/menu.png"))); // NOI18N
        jPanel1.add(SideMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 47, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 915, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getAccessibleContext().setAccessibleName("tablita");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void CerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CerrarSesionActionPerformed
        Login login = new Login();
        this.setVisible(false);
        login.setVisible(true);
    }//GEN-LAST:event_CerrarSesionActionPerformed

    private void agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarActionPerformed
        Agregar();
        consultar();
    }//GEN-LAST:event_agregarActionPerformed

    private void LimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LimpiarActionPerformed
        ID.setText("");
        userName.setText("");
        name.setText("");
        telephone.setText("");
        email.setText("");
        Password.setText("");
    }//GEN-LAST:event_LimpiarActionPerformed

    private void ContenedorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ContenedorMouseClicked
        int fila = Contenedor.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(null, "No se selecciono ninguna fila");
        } else {
            int idc = Integer.parseInt((String) Contenedor.getValueAt(fila, 0).toString());
            String Usuario = (String) Contenedor.getValueAt(fila,1);
            String Nombre = (String) Contenedor.getValueAt(fila,2);
            String Telefono = (String) Contenedor.getValueAt(fila,3);
            String Correo = (String) Contenedor.getValueAt(fila,4);
            String Contrasena = (String) Contenedor.getValueAt(fila,5);
         
            ID.setText(""+idc);
            userName.setText(Usuario);
            name.setText(Nombre);
            telephone.setText(Telefono);
            email.setText(Correo);
            Password.setText(Contrasena);
        }
    }//GEN-LAST:event_ContenedorMouseClicked

    private void editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarActionPerformed
        Modificar();
        consultar();
    }//GEN-LAST:event_editarActionPerformed

    private void eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarActionPerformed
        Eliminar();
        consultar();
    }//GEN-LAST:event_eliminarActionPerformed
    
    void Modificar(){
        String Usuario = userName.getText();
        String Nombre = name.getText();
        String Telefono = telephone.getText();
        String Correo = email.getText();
        String Contrasena = new String(Password.getPassword());
        
        int fila = Contenedor.getSelectedRow();
        int idc = Integer.parseInt((String) Contenedor.getValueAt(fila, 0).toString());
        
        try {
            if (Usuario.equals("") || Nombre.equals("") || Telefono.equals("") || Correo.equals("") || Contrasena.equals("")){
                JOptionPane.showMessageDialog(null, "Faltan ingresar datos");
                limpiarTabla();
            } else {
                String sql = "UPDATE administrador set idAdmin ='"+idc+"', nombreUsuario = '"+Usuario+"', nombreCompleto = '"+Nombre+"', telefono = '"+Telefono+"', correo = '"+Correo+"', contrasena = '"+Contrasena+"' where idAdmin = " +idc;
                Connection conet = con1.conexion();
                st = conet.createStatement();
                st.executeUpdate(sql);
                JOptionPane.showMessageDialog(null, "Usuario modificado Correctamente!");
                limpiarTabla();
            }
        } catch (Exception e) {
            System.out.println("Ocurrio un problema" +e );
        }
    }
    
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tabla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tabla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tabla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tabla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tabla().setVisible(true);
            }
        });
    }
    
    void consultar(){
        String sql = "Select * from administrador";
        
        try {
            Connection conet = con1.conexion();
            /*conet = con1.getConnection();*/
            st = conet.createStatement();
            rs = st.executeQuery(sql);
            
            Object[] admin = new Object[6];
            modelo = (DefaultTableModel) Contenedor.getModel();
            while (rs.next()){
                admin [0] = rs.getInt("idAdmin");
                admin [1] = rs.getString("nombreUsuario");
                admin [2] = rs.getString("nombreCompleto");
                admin [3] = rs.getString("telefono");
                admin [4] = rs.getString("correo");
                admin [5] = rs.getString("contrasena");
                
                modelo.addRow(admin);
            }
            Contenedor.setModel(modelo);
            
        } catch (Exception e){
            System.out.println("Ocurrio un problema con los datos de la tabla: "+e);
        }    
    }
    
    void Agregar(){
        String Usuario = userName.getText();
        String Nombre = name.getText();
        String Telefono = telephone.getText();
        String Correo = email.getText();
        String Contrasena = new String(Password.getPassword());
        
        try {
            if (Usuario.equals("") || Nombre.equals("") || Telefono.equals("") || Correo.equals("") || Contrasena.equals("")){
                JOptionPane.showMessageDialog(null, "Faltan ingresar datos");
                limpiarTabla();
            } else {
                /*
                String sql = "insert into administrador values (null, '"+Nombre+"', '"+Telefono+"','"+Correo+"','"+Contrasena+"')";
                */
                try {
                    Connection con = con1.conexion();
                    PreparedStatement pps = con.prepareStatement("INSERT INTO administrador(nombreUsuario, nombreCompleto, telefono, correo, contrasena) VALUES (?,?,?,?,?)");
                    pps.setString(1, Usuario);
                    pps.setString(2, Nombre);
                    pps.setString(3, Telefono);
                    pps.setString(4, Correo);
                    pps.setString(5, Contrasena);
                    pps.executeUpdate();
                    JOptionPane.showMessageDialog(null, "Registrado Correctamente!");
                    limpiarTabla();
                } catch (SQLException ex) {
                    Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        } catch (Exception e) {
            System.out.println("Columnas o filas = " + Contenedor.getRowCount() );
            System.out.println("Ocurrio un problema" +e );
        }    
    }
    
    void limpiarTabla(){
        for (int i=0; i <= Contenedor.getRowCount(); i++){
            modelo.removeRow(i);
            i = i-1;
        }
    }
    
    void Eliminar(){
        int fila = Contenedor.getSelectedRow();
        int idc = Integer.parseInt((String) Contenedor.getValueAt(fila, 0).toString());
        
        try{
            if (fila < 0) {
                JOptionPane.showMessageDialog(null, "Usuario no seleccionado");
                limpiarTabla();
            } else {
                String sql = "DELETE from administrador where idAdmin="+idc;
                Connection conet = con1.conexion();
                st = conet.createStatement();
                st.executeUpdate(sql);
                JOptionPane.showMessageDialog(null, "Se a eliminado Correctamente!");
                limpiarTabla();
            }
        } catch (Exception e){
            System.out.println("Ocurrio un error"+e);
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CerrarSesion;
    private javax.swing.JTable Contenedor;
    private javax.swing.JTextField ID;
    private javax.swing.JButton Limpiar;
    private javax.swing.JPasswordField Password;
    private javax.swing.JLabel SideMenu;
    private javax.swing.JLabel Subtitulo;
    private javax.swing.JButton agregar;
    private javax.swing.JButton editar;
    private javax.swing.JButton eliminar;
    private javax.swing.JTextField email;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField name;
    private javax.swing.JTextField telephone;
    private javax.swing.JTextField userName;
    // End of variables declaration//GEN-END:variables
}
